### ISSUE TITLE
CORS Issues

### ISSUE THREAD

**Issue by russmatt** [bgrnwd/fotmob#357]
**Describe the bug**
Every API call is blocked by CORS policy

**To Reproduce**
1. Create a new Angular Project
2. Install package
3. Do any http call
4. Error Access to XMLHttpRequest at 'https://www.fotmob.com/api/matchDetails?matchId=3917969' from origin 'https://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Expected behavior**
JSON result to be printed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version Last stable

**Comment by ItamarShDev** [comment]
This package is supposed to be used from the server.
Maybe we should add it to the docs? @bgrnwd

**Comment by bgrnwd** [comment]
Yeah, let's add it
