### ISSUE TITLE
Simple Questions

### ISSUE THREAD

**Issue by ErwinKim** [bgrnwd/fotmob#499]
Hello, 

Thanks for your work it's really amazing. However, I don't really get the way to start this project. Can you provide the details of starting this project?? 

Best, 
Erwin

**Comment by ItamarShDev** [comment]
Sure!

This is a NodeJS package. that you can install and use easily.
In you Node/Full stack project you just need to:
1. Install it `npm i fotmob`
2. Import it in the needed file `import Fotmbo from 'fotmob'`
3. await any action you need from the package 
```typescript
import Fotmob from 'fotmob';

const fot = new Fotmob();

async function myHandler(...) {
    const player = await fot.getPlayer(432);
....
}
```


Here is a codesandbox with Remix using this library https://codesandbox.io/p/devbox/jwm3kx?embed=1&file=%2Fapp%2FgetPlayer%2Faction.ts%3A13%2C28-13%2C37

**Comment by ErwinKim** [comment]
Thank you so much for your reply!

2024년 10월 24일 (목) 오후 6:26, itamar sharify ***@***.***>님이 작성:

**Comment by ItamarShDev** [comment]
You are very welcome, if the problem resolved, please close this issue. :)
